project_name: prometheus-junos-exporter
dist: artifacts

before:
   hooks:
     - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - freebsd
    goarch:
    - amd64
    - arm
    - arm64
    ignore:
    - goos: freebsd
      goarch: arm64
    ldflags: -s -w -X main.version={{.Version}}
    binary: junos_exporter

nfpms:
  - homepage:  https://github.com/czerwonk/junos_exporter
    description: JunOS Exporter for Prometheus
    maintainer: Daniel Czerwonk
    license: MIT License
    contents:
      - src: .packaging/defaults
        dst: /etc/default/prometheus-junos-exporter
      - src: .packaging/prometheus-junos-exporter.service
        dst: /usr/lib/systemd/system/prometheus-junos-exporter.service
    formats:
      - deb
    dependencies:
      - systemd
    scripts:
        postinstall: .packaging/postinstall.sh