{
 "title": "SRX Firewall",
 "description": "State of the SRX cluster and the compute nodes underneath",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "device", "label": "Device", "query": { "query": "label_values(junos_up,target)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Basic system info",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(max by (hostname, model, os_version, target) (junos_system_hardware_info{target=\"${device}\"}) * 0) + on (target) group_left junos_system_license_installed{target=\"${device}\", feature_name=\"vcpu scale\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(junos_system_license_expiry{target=\"${device}\"}) * 24 * 60 * 60",
     "legendFormat": "time until expiration"
    }
   ]
  },
  {
   "title": "SRX nodes up",
   "type": "stat",
   "description": "How many SRX nodes are running",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sum by (pod) (last_over_time(junos_environment_power_up{target=\"${device}\", status=\"OK\"}[5m])))",
     "legendFormat": "vSRX nodes"
    }
   ]
  },
  {
   "title": "SRX uptime",
   "type": "stat",
   "description": "How long each SRX node has been running since the last reboot",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (re_name) (junos_route_engine_uptime_seconds{target=\"${device}\"})",
     "legendFormat": "{{re_name}}"
    }
   ]
  },
  {
   "title": "SRX yellow alarms",
   "type": "stat",
   "description": "Number of warning-type alerts from Junos OS",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(junos_alarms_yellow_count{target=\"${device}\"})",
     "legendFormat": "Yellow alarms"
    }
   ]
  },
  {
   "title": "SRX red alarms",
   "type": "stat",
   "description": "Number of high-importance alerts from Junos OS",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(junos_alarms_red_count{target=\"${device}\"})",
     "legendFormat": "Red alarms"
    }
   ]
  },
  {
   "title": "SRX RE load averages",
   "type": "timeseries",
   "description": "1, 5 and 15-minute load averages of Routing Engine system of SRX nodes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (re_name) (junos_route_engine_load_average_one{target=\"${device}\"})",
     "legendFormat": "la1: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_load_average_five{target=\"${device}\"})",
     "legendFormat": "la5: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_load_average_fifteen{target=\"${device}\"})",
     "legendFormat": "la15: {{re_name}}"
    }
   ]
  },
  {
   "title": "SRX system alarm details",
   "type": "table",
   "description": "List of alerts reported by Junos OS",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (class, type, description) (junos_alarms_set{target=\"${device}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SRX Controlplane HA",
   "type": "table",
   "description": "Statuses reported by Junos OS for each controlplane redundancy group node instance",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "junos_chassis_cluster_node_status{target=\"${device}\",redundancy_group=\"0\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Routing Engines status",
   "type": "table",
   "description": "Statuses reported by Junos OS for each Routing Engine instance",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "max by (re_name) (junos_route_engine_status{target=\"${device}\"})",
     "legendFormat": "{{re_name}}"
    }
   ]
  },
  {
   "title": "CPU time %",
   "type": "timeseries",
   "description": "CPU time used by type and node",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (re_name) (junos_route_engine_cpu_system_percent{target=\"${device}\"})",
     "legendFormat": "system: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_cpu_user_percent{target=\"${device}\"})",
     "legendFormat": "user: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_cpu_background_percent{target=\"${device}\"})",
     "legendFormat": "background: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_cpu_interrupt_percent{target=\"${device}\"})",
     "legendFormat": "interrupt: {{re_name}}"
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "timeseries",
   "description": "Memory used by control/data planes of Routing Engine as a percentage of total, per node",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (re_name) (junos_route_engine_memory_data_plane_used_bytes{target=\"${device}\"} / junos_route_engine_memory_system_total_bytes{target=\"${device}\"} * 100)",
     "legendFormat": "dataplane: {{re_name}}"
    },
    {
     "expr": "max by (re_name) (junos_route_engine_memory_control_plane_used_bytes{target=\"${device}\"} / junos_route_engine_memory_system_total_bytes{target=\"${device}\"} * 100)",
     "legendFormat": "controlplane: {{re_name}}"
    }
   ]
  },
  {
   "title": "Active routes in tables",
   "type": "timeseries",
   "description": "Number of active routes for each defined routing table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max by (table) (junos_routes_active_count{target=\"${device}\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Scrape timings",
   "type": "timeseries",
   "description": "How long it took for every individual Junos OS exporter scrape to complete",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (target) (junos_collector_duration_seconds{target=\"${device}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Security policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Connection rate by policy (internal networks)",
   "type": "timeseries",
   "description": "Rate of outgoing connections through SRX firewall, grouped by source/destination and the applied traffic policy. Does not include internet policies.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "con/s" } },
   "targets": [
    {
     "expr": "max by (policy_name, from_zone, to_zone) (irate(junos_security_policies_hit_count{target=\"${device}\", from_zone!~\".*LOOPBACK\", to_zone!~\".*LOOPBACK\",policy_name!=\"INTERNET\"}[5m]))",
     "legendFormat": "{{from_zone}}->{{to_zone}}: {{policy_name}}"
    }
   ]
  },
  {
   "title": "Internet policy connection rate",
   "type": "timeseries",
   "description": "Rate of outgoing internet connections through SRX firewall",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "con/s" } },
   "targets": [
    {
     "expr": "max by (policy_name, from_zone, to_zone) (irate(junos_security_policies_hit_count{target=\"${device}\", from_zone!~\".*LOOPBACK\", to_zone!~\".*LOOPBACK\", policy_name=\"INTERNET\"}[5m]))",
     "legendFormat": "{{from_zone}}->{{to_zone}}: {{policy_name}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Interface queues packet rate",
   "type": "timeseries",
   "description": "Packets per second across all interface queues, by action taken",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_transfered_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "transferred"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_queued_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_drop_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "dropped"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_rate_limit_drop_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "rate-limited"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_red_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "red-dropped"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_tail_drop_packets_count{target=\"${device}\"}[5m])))",
     "legendFormat": "tail-dropped"
    }
   ]
  },
  {
   "title": "Interface queues data rate",
   "type": "timeseries",
   "description": "Bytes per second across all interface queues, by action taken",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_transfered_bytes_count{target=\"${device}\"}[5m])))",
     "legendFormat": "transferred"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_queued_bytes_count{target=\"${device}\"}[5m])))",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_drop_bytes_count{target=\"${device}\"}[5m])))",
     "legendFormat": "dropped"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_rate_limit_drop_bytes_count{target=\"${device}\"}[5m])))",
     "legendFormat": "rate-limited"
    },
    {
     "expr": "sum(max by (name) (irate(junos_interface_queues_red_bytes_count{target=\"${device}\"}[5m])))",
     "legendFormat": "red-dropped"
    }
   ]
  },
  {
   "title": "Rx/Tx packet rate",
   "type": "timeseries",
   "description": "Interface receive/transmit packets per second, only shown for interfaces with any traffic during the chosen period",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "max by (name) (irate(junos_interface_receive_packets_total{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "Rx: {{name}}"
    },
    {
     "expr": "-(max by (name) (irate(junos_interface_transmit_packets_total{target=\"${device}\"}[5m])) > 0)",
     "legendFormat": "Tx: {{name}}"
    }
   ]
  },
  {
   "title": "Rx/Tx data rate",
   "type": "timeseries",
   "description": "Interface receive/transmit bytes per second, only shown for interfaces with any traffic during the chosen period",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (name) (irate(junos_interface_receive_bytes{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "Rx: {{name}}"
    },
    {
     "expr": "-(max by (name) (irate(junos_interface_transmit_bytes{target=\"${device}\"}[5m])) > 0)",
     "legendFormat": "Tx: {{name}}"
    }
   ]
  },
  {
   "title": "Rx/Tx error rate",
   "type": "timeseries",
   "description": "Interface receive/transmit errors per second, only shown for interfaces with errors during the chosen period",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "max by (name) (irate(junos_interface_receive_errors{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "Rx: {{name}}"
    },
    {
     "expr": "-(max by (name) (irate(junos_interface_transmit_errors{target=\"${device}\"}[5m])) > 0)",
     "legendFormat": "Tx: {{name}}"
    }
   ]
  },
  {
   "title": "Rx/Tx drop rate",
   "type": "timeseries",
   "description": "Interface receive/transmit drops per second, only shown for interfaces with drops during the chosen period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "max by (name) (irate(junos_interface_receive_drops{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "Rx: {{name}}"
    },
    {
     "expr": "-(max by (name) (irate(junos_interface_transmit_drops{target=\"${device}\"}[5m])) > 0)",
     "legendFormat": "Tx: {{name}}"
    }
   ]
  },
  {
   "title": "Rx abnormal frame rate",
   "type": "timeseries",
   "description": "Rates of interface frames that are not normal, only shown for interfaces with abnormal frames during the chosen period, grouped by interface and the frame type",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "frames/s" } },
   "targets": [
    {
     "expr": "max by (name) (irate(junos_interface_receive_oversized_frames{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "{{name}}: oversized"
    },
    {
     "expr": "max by (name) (irate(junos_interface_receive_jabber_frames{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "{{name}}: jabber"
    },
    {
     "expr": "max by (name) (irate(junos_interface_receive_fragment_frames{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "{{name}}: fragmented"
    },
    {
     "expr": "max by (name) (irate(junos_interface_receive_vlan_tagged_frames{target=\"${device}\"}[5m])) > 0",
     "legendFormat": "{{name}}: tagged"
    }
   ]
  },
  {
   "title": "Interface details",
   "type": "table",
   "description": "Detailed interface speed, MTU, error and state information",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "max by (name) (junos_interface_speed{target=\"${device}\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (name) (junos_interface_mtu{target=\"${device}\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (name) (junos_interface_error_status{target=\"${device}\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (name) (junos_interface_admin_up{target=\"${device}\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "-(max by (name) (junos_interface_last_flapped_seconds{target=\"${device}\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "BGP sessions up",
   "type": "stat",
   "description": "How many BGP sessions are up and running",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (ip, group, description) (last_over_time(junos_bgp_session_up{target=\"${device}\"}[5m])))",
     "legendFormat": "BGP sessions"
    }
   ]
  },
  {
   "title": "BGP prefixes advertised",
   "type": "stat",
   "description": "How many BGP prefixes are being advertised in total (non-unique, to all peers)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (ip, group, description) (last_over_time(junos_bgp_session_prefixes_advertised_count{target=\"${device}\"}[5m])))",
     "legendFormat": "BGP prefixes"
    }
   ]
  },
  {
   "title": "BGP prefixes received",
   "type": "stat",
   "description": "How many BGP prefixes have been received in total (non-unique, from all peers)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (ip, group, description) (last_over_time(junos_bgp_session_prefixes_received_count{target=\"${device}\"}[5m])))",
     "legendFormat": "BGP prefixes"
    }
   ]
  },
  {
   "title": "BGP routes active",
   "type": "stat",
   "description": "How many BGP-announced routes are active",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min by (table) (last_over_time(junos_routes_protocol_active_count{target=\"${device}\", protocol=\"BGP\"}[5m])))",
     "legendFormat": "BGP routes"
    }
   ]
  },
  {
   "title": "BGP sessions",
   "type": "table",
   "description": "Detailed information about configured BGP sessions",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "max by (group, ip) (junos_bgp_session_up{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (group, ip) (junos_bgp_session_state{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ip, group, options, description) (junos_bgp_session_info{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ip, group) (junos_bgp_session_flap_count{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ip, group) (junos_bgp_session_prefixes_advertised_count{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ip, group) (junos_bgp_session_prefixes_received_count{target=\"${device}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ip, group) (junos_bgp_session_prefixes_active_count{target=\"${device}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}