{
 "title": "Juniper",
 "tags": [ "newtelco" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "int_desc", "label": "Interface Description", "query": "junos_interface_up" },
   { "name": "device", "label": "device", "query": "junos_up" }
  ]
 },
 "panels": [
  {
   "title": "Red Alarms",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "junos_alarms_red_count{target=\"172.16.4.100\"}"
    }
   ]
  },
  {
   "title": "Yellow Alarms",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "junos_alarms_yellow_count{target=\"172.16.4.100\"}"
    }
   ]
  },
  {
   "title": "Root FS ",
   "type": "gauge",
   "description": "Root Filesystem Usage",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "junos_storage_used_percent{mountpoint=~\"/\",target=~\"$device\"}"
    }
   ]
  },
  {
   "title": "$device",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "junos_up{target=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Rx vs Tx Bytes ($int_desc)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "repeat": "int_desc",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(junos_interface_transmit_bytes{description=\"$int_desc\"}[5m])",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(junos_interface_receive_bytes{description=\"$int_desc\"}[5m])",
     "legendFormat": "Rx"
    }
   ]
  }
 ]
}